### ISSUE TITLE
soccr question glitch, missing text

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#111]
If you past the soccr question and then go back it has trouble going back prior to soccr question and instead of the button saying 'back' is says '19-4031'. It gets stuck in a loop.

Missing question text for OCCUPTN1

**Comment by ruggz13** [comment]
On reload, pressing previous will go back to question where SOCcer populates the question. Nothing was typed in...but value is saved... doesn't populate the question and makes the "back" button the value of the SOCcer code
SOCcer Problem, not QUEST

**Comment by danielruss** [comment]
I think this is a problem with the interaction between simpletest (PWA prototype) and quest.

**Comment by danielruss** [comment]
The problem was in localForage.  The SOCcer question is actually an empty question as far as quest is concerned.  We paint the question on to a blank question.  However, when you return to the survey at a later point, LF tries to assign the value to an input element.  That input element is the previous button.  I stopped it from writing over a submit button.
