### ISSUE TITLE
Module 3 - Age range syntax

### ISSUE THREAD

**Issue by joshid-ims** [episphere/quest#132]
[CIGLIFEA – CIGLIFEH] On days that you smoked when you were age [X] [to age Y], about how many cigarettes did you smoke per day? 
□ Age [X] to age [Y / 17] |__|__| #CIGARETTES PER DAY [X= [VALUE AT CIG3]
Y= [IF CIG4=01 OR CIG7B=01 THEN 17 OR CURRENT AGE, WHICHEVER IS LOWEST VALUE] OR [IF CIG8C=01 THEN SET TO VALUE AT CIG8]

Can you please explain the logic of these questions and syntax of the script for them?

**Comment by danielruss** [comment]
This question a little complex.  In module one, we handled a question similarly by breaking it up into multiple questions.  It also deals with a bit of complexity in the values.

I am having a hard time following the logic myself, so I am asking one of our questionnaire experts to the issue

**Comment by danielruss** [comment]
@ashreves , In Module3 question T13, I assume that you are trying to set an age range from X to Y.  If I started at 18 and I am currently 40,  The range is from 18->20 correct?  It appears to ask us to set Y to 17.  This is confusing me.

**Comment by danielruss** [comment]
also we have a syntax that you need to be aware of (that is not in the wiki yet).  The users current age is stored as  age, however if the user corrected his age in Module 1, it is stored as AGE.  so you should use the syntax  ifdefined(AGE,age) when you need the age.  If AGE is define, AGE is used; otherwise, age is used.

**Comment by danielruss** [comment]
Forgot to mention that if there are multiple age ranges, see Module 1 WTLOSS1_1825. it's in github

**Comment by ashreves** [comment]
@danielruss 

Participants should be asked a question about each group of ages that falls between the smoking start age and smoking stop age or current age (if current smoker)

The age rages are (age below 17-17, 18-24, 25-29, 30-39, 40-49, 50-59, 60-69, 70- age above 70).

However, the high and low of each age range should be adjusted for years smoking and adjusted for age of participant. 

For example, if a 65 year old current smoker started smoking at age 41, they should be asked about the following years:
1. 41-49
2. 50-59
3. 60-65

As another example, if a 55 year old participant started smoking at age 14 and stopped smoking at age 16, they would only get asked the following:
1. 14-16

**Comment by ashreves** [comment]
@danielruss 

There is one additional note- [CIGLIFE AGE RANGE: IF RESPONDENT'S CURRENT AGE IS 2 YEARS OR LESS FROM THE BOTTOM OF THE SPECIFIED AGE RANGE, THEY SHOULD NOT BE GIVEN THE QUESTION AND INSTEAD ROUTED TO ECIG1.] 

As an example, if a participant is 61 years old, we do not want to ask them about their smoking behaviors for the age range 60-61 since they have already told us about their current behaviors. The last category that we would ask them about is the previous age group, 50-59.

**Comment by danielruss** [comment]
Thank you @ashreves 

@joshid-ims I would unroll all the question [see comments above]

CIGLIF_UPTO17,
CIGLIF_18TO24,
...
CIGLIFE_OVER70 

Using the displayif on the question only display question that are appropriate to the users age.  Remember that users will be over 40, so you dont need to check age for groups under 40, but you have to check that the started smoking is before the group and if they stopped smoking.  The displayif may get complicated.  Don't forget you can use (isDefined(VAR,default))..

If you have trouble, feel free to ask for help.
