### ISSUE TITLE
Module 2: If No response/ fill

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#134]
SLEEP1A - - [IF SLEEPSCHA=01, FILL “the nights before workdays”. IF SLEEPSCHA=00, NON-RESPONSE, FILL “most days”]

**Comment by danielruss** [comment]
ugh...  
so there are 3 options,   1) the user selects 1; 2) the user select 2; 3) the user does not select anything.  

if the user select 1 you should be able to handle it with |displayif=equals(VAR,1)|the night before weekend| 

I see two different ways of handling the no response.  
SOLUTION 1:
|displayif=isDefined(VAR,2)| most days|

explanation:  Your question, VAR, has an undefined value if the user does not respond. By using the isDefined function, we set the function response to "2" if the value is undefined.  Note that if VAR is 2 the function also returns "2".  So you now handled both the NR and VAR=2 case.


SOLUTION 2:  (requires Nick to fix)
|displayif=equals(VAR,1)| TEXT TO DISPLAY | TEXT TO DISPLAY IF FALSE|

Up to Nick if he want to deal with this...

**Comment by danielruss** [comment]
@meekk1 did I answer your question?

**Comment by meekk1** [comment]
So I can get it to work if there is no response. But if the user responds with YES, conditional text doesn't work. All text is shown. My markdown is here:

https://gist.github.com/meekk1/9bdffd045d6b69781c3ee6228403a650

**Comment by danielruss** [comment]
@meekk1 The main problem in the gist is on the 
[INTRO2,displayif=isDefined(SLEEPSCHA,2)] We have some questions about your sleep schedule. Please answer these questions thinking about your usual day.

you're checking if SLEEPSCHA is defined (which it is) and returning the value of the variable.  What you want to do is

[INTRO2,displayif=equals(isDefined(SLEEPSCHA,2),2)] We have some questions about your sleep schedule. Please answer these questions thinking about your usual day.

or better just

[INTRO2,displayif=equals(SLEEPSCHA,2)] We have some questions about your sleep schedule. Please answer these questions thinking about your usual day.

Why?  The first case looks to see if SLEEPCHA is defined, if it is it returns the value, otherwise it return the value 2.  Then it checks if the value equals 2.

The second case just checks if the variable is 2. (which is what you want).  

Now if you were using SLEEPCHB, the question may never appear, so you should check using isDefined and supply a default value.

**Comment by danielruss** [comment]
let me know if i've answered your question, or just close the issue.

**Comment by meekk1** [comment]
[INTRO2,displayif=equals(SLEEPSCHA,2)] does not work for me. It skips INTRO2 if the user does NO RESPONSE on [SLEEPSCHA]

[INTRO2,displayif=equals(isDefined(SLEEPSCHA,2),2)] works but when the user selects YES on [SLEEPSCHA], this is how it looks

![image](https://user-images.githubusercontent.com/64271614/85422533-b86fea80-b543-11ea-89ea-e56f81b253c3.png)

![image](https://user-images.githubusercontent.com/64271614/85422740-ee14d380-b543-11ea-8a15-3ed485e46eb2.png)

**Comment by danielruss** [comment]
you need the equals in the displayif in [SLEEP1A] also

|displayif=equals(isDefined(SLEEPCHA,2),2)|most days|

WARNING:  Only use this if you want the user to see "most days" by default.  If there was a third option when nothing was selected then
 equals(isDefined(SLEEPCHA,3),1)|nights before workdays|
 equals(isDefined(SLEEPCHA,3),2)|most days|
 equals(isDefined(SLEEPCHA,3),3)|NOT SELECTED OPTION|

is that clear?

**Comment by meekk1** [comment]
Ok, that makes sense.

But when the user selects YES in they still get both INTROs and "the nights before workdaysmost days" in [SLEEP1A]

**Comment by danielruss** [comment]
[SLEEPSCHA] During a usual week, is your sleep schedule determined by your job, school, or 
other activities?
(1)Yes
(0)No -> INTROSLESCH1
< #NR -> INTROSLESCH1>


[SLEEPSCHB]  How many days per week do your job, school, or other activities determine your sleep schedule?
(1)1
(2)2
(3)3
(4)4
(5)5
(6)6
(7)7

[INTROSLESCH1] |displayif=equals(isDefined(SLEEPSCHA,0),1)|We have some questions about your sleep schedule on workdays. Workdays include days when you do any type of work that includes a schedule, for example, working for pay outside the home or working as a homemaker. ||displayif=equals(isDefined(SLEEPSCHA,0),0)|We have some questions about your sleep schedule. Please answer these questions thinking about your usual day.|

**Comment by danielruss** [comment]
This is how I would have handled it.

**Comment by meekk1** [comment]
Added your INTROS in. Now [SLEEP1A] doesn't render at all. So I changed it to this. Not sure what my problem is.

[SLEEP1A] What time do you usually go to bed on |displayif=equals(isDefined(SLEEPSCHA,0),1)|the nights before workdays||displayif=equals(isDefined(SLEEPCHA,0),0)|most days|? Please tell us the time you usually get into your bed, not the time you usually fall asleep. Select your answer using the drop-downs below.

**Comment by danielruss** [comment]
The variable is SLEEPSCHA not SLEEPCHA.  you left off an "S"

**Comment by meekk1** [comment]
Thank you!!!

**Comment by meekk1** [comment]
Has the user selecting NO on [SLEEPSCHA] been defined? When I select NO for [SLEEPSCHA],  I get this on SLEEP1A:
![image](https://user-images.githubusercontent.com/64271614/85455757-39db7300-b56c-11ea-8585-16e1a033d976.png)

Sorry this has been so much trouble. My gist is here: https://gist.github.com/meekk1/9bdffd045d6b69781c3ee6228403a650

**Comment by danielruss** [comment]
change your displayif to:
|displayif=equals(isDefined(SLEEPSCHA,0),1)|the nights before workdays||displayif=equals(isDefined(SLEEPSCHA,0),0)|

explaination:
equals(isDefined(SLEEPSCHA,0),1).  <- if SLEEPSCHA is Defined use the value, otherwise, use 0.  does that value ==1
equals(isDefined(SLEEPSCHA,0),0)  <- if SLEEPSCHA is Defined use the value, otherwise, use 0.  does that value ==0

**Comment by danielruss** [comment]
> Sorry this has been so much trouble.

You are not causing trouble.  Please close the issue if it is resolved.  Feel free to create new issues if you have new questions.

**Comment by meekk1** [comment]
Thanks, it works.
