### ISSUE TITLE
Module 4: Complex Loop

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#144]
In [HOMEADDSUM]: 
![image](https://user-images.githubusercontent.com/64271614/85296614-a886d680-b46f-11ea-9bda-88607a9644fe.png)

**Comment by danielruss** [comment]
similar to #143

**Comment by danielruss** [comment]
@meekk1 I am waiting to hear from Alaina, who is probably waiting to hear from the PI responsible for this question.

**Comment by danielruss** [comment]
for this loop, if yes is selected, HOMEADD1 is the first question of the loop.  Since this question is the last question in the loop, you don't need to add anything to the queue.  However, if No or #NR  is selected, you should just to HOMEMOVEIN which is after the loop

(1) YES
(2) No -> HOMEMOVEIN
\< #NR -> HOMEMOVEIN >
