### ISSUE TITLE
Module 3 - complex logic

### ISSUE THREAD

**Issue by joshid-ims** [episphere/quest#177]
Another complex logic I am struggling with is

IF (CIG4 = 01) OR ((CIG4 = 02, 03, OR 04) AND CIG5 = 02 AND CIG7B = 01) OR ((CIG4 = 02, 03, OR 04) AND CIG5 = 03 AND CIG8C = 01), GO TO CIG10
ELSE, GO TO CIG9B

**Comment by danielruss** [comment]
ok that took a long time.  There were a lot of questions that I had to do in order to set the logic up...

check out this gist...
https://gist.github.com/danielruss/1b97235471dd34a1c4b5c6887fae9e58

Note that the logic to ASK the question is  (which is the inverse of skipping the question)
1.  You dont current smoke everyday... (CIG4!=1)
2.  if you smoked over the past 30 days you didnt smoke everyday...
3.  if you smoke longer than 30 days ago you didn't smoke everyday.
(this is to make sure you aren't ask if your ever smoked, when you already answered that you did)

displayif=and(greaterThan(isDefined(CIG4,5),1),and(equals(isDefined(CIG7B,0),0),equals(isDefined(CIG8C,0),0)))

Here is the explanation..

CASE1: greaterThan(isDefined(CIG4,5),1)  <=. if CIG4 is defined, use the variable, otherwise set it to 5, and check that the value is greater than 1.    This checks that CIG4 is NOT 1.

CASE2: equals(isDefined(CIG7B,0),0) <=  if CIG7B is not defined set it to 0, and check that it equals 0.   This checks that CIG7B is NO or No Response (Not YES)

CASE3: equals(isDefined(CIG8C,0),0) <= same logic except for 8C

and(CASE1, and(CASE2,CASE3))  <- ALL of these must be true to display the question.

One last rub...  This is inside a larger set of questions.  What tobacco products you are using.  Every question MUST have an arrow ( -> ) to tell where to go next, otherwise it will jump to the next product.  Notice in question CIG9B I dont put an arrow to ECIG1.  If you didnt select ECIG1, it wont go there, it will go to [END] in my case.   

One more last rub...  the displayif is very fussy...  DO NOT PUT IN ANY SPACES.  crazy stuff ensues... We need to fix this at some point.
