### ISSUE TITLE
Module 2 - Can select radio button without filling in required text

### ISSUE THREAD

**Issue by cyrjeant** [episphere/quest#235]
The user shouldn't be able to just select a radio button option to continue. They should have to fill in the text box and then the radio button to continue.  We saw this issue back in November, then we saw it get fixed, and now we are seeing it again.  
![image](https://user-images.githubusercontent.com/64271080/103226451-28e43380-48fa-11eb-900f-5d0008263218.png)

**Comment by cyrjeant** [comment]
We also noted what looks to be a similar but different problem - user can fill in text, but be allowed to move on without selecting the radio button
![image 2](https://user-images.githubusercontent.com/64271080/103226586-75c80a00-48fa-11eb-8128-6a1fad9fa0fa.png)

**Comment by hzhao392** [comment]
@cyrjeant Hi Jean, can you attach the snippet of code that is having this issue? Or if it's commited to the main branch please send the module number and the question_id

**Comment by hzhao392** [comment]
@cyrjeant you are right, this was fixed in November. The syntax for these kind of questions look like this

[ACIDSUP2_1?] During the time(s) that you were taking abc, about how many <b>days per week or month</b> did you take it?
(1) #Days PER Week |__|__|min=1 max=7| 
(2) #Days PER Month |__|__|min=1 max=31| 

You are forced to pick a radio button first, then the content of the radio button
