### ISSUE TITLE
Module 2 - HOUSE1 Intro text

### ISSUE THREAD

**Issue by ashreves** [episphere/quest#287]
Please make HOUSE1 intro text display on same screen as grid question, not on its own screen.

**Comment by stealthv** [comment]
We can't do this with the existing text. The problem is that intro text has a displayif statement in it.
`During the <b>past 12 months</b>, about how often did you do each of these household or shopping activities |displayif=equals(WORK,1)|outside of work|?`

Trying to use that within the heading text for a grid causes the grid to fail. It seems either the text will need to be changed or it will have to remain separate.

**Comment by ashreves** [comment]
@robertsamm This is a UI/UX issue. I think we should table it for now and readdress it during PWA testing. What do you think?

**Comment by robertsamm** [comment]
@ashreves That is fine. Do we have a column for issues that we'll be addressing later?

**Comment by ashreves** [comment]
@robertsamm I am not sure we have a dedicated column.

@hzhao392 What do you think?

**Comment by ashreves** [comment]
@hzhao392 Can we add a column to the project board for issues that we are addressing later?

**Comment by danielruss** [comment]
stale ... closed
