### ISSUE TITLE
Inconsistent variable names created within loops

### ISSUE THREAD

**Issue by huip-ims** [episphere/quest#390]
@danielruss @boyd-mj @huip-ims Hi Daniel – We are seeing some inconsistent variable names created by quest within loops and are hoping you can help us understand why this is happening.

In the biospecimen survey, there is a COVID-19 loop. During each iteration of the loop, some Quest IDs are used to create variable names with “_1”, “_2”, “_3”, & etc. However, other Quests IDs within the same loop are used to create variable names with “_1_1”, “_2_2”, “_3_3”, & etc. Do you know why “_1_1” would be used in some situations rather than “_1”? See examples in screenshot below.

![image](https://user-images.githubusercontent.com/82978291/164145891-0c9409c8-2e4e-44c0-9899-b26529a25e9b.png)

**Comment by danielruss** [comment]
I think you see _1 sometimes and _1_1 at other times because the question ids are getting the _1_1, and |__|id=xxx| becomes 
 xxx_1, xxx_2.  

As I said, this is an implementation flaw, but it works.  We could fix it at the risk of breaking it.  Hence, I never saw the value in fixing it.  We are hoping to fix this in the future.  (However, we need to loop in Nichole because it WILL have an effect on connect.

**Comment by boyd-mj** [comment]
No changes requested. If this changes with Quest 2.0, please let us know so we can make adjustments to the transformer software as needed. Thanks!
