### ISSUE TITLE
If/Else statement

### ISSUE THREAD

**Issue by meekk1** [episphere/quest#77]
Syntax for situations like this??? Where does the else statement go?

For example:
[DISPLAY 1_PROGHOR6 IF 01 WAS SELECTED AT PROGHOR]
**[ELSE, GO TO 2_PROGHOR6]**
 
[1PROGHOR6,displayif=equals(PROGHOR1,1)] How many days per cycle did you use this oral progestin-only hormone?|
(1)	Less than 10 days per month
(2)	10 to 14 days per month
(3)    15 to 19 days per month
(4)	20 to 25 days per month
(5)	Every day
< #NR -> 2_PROGHOR6 >

**Comment by danielruss** [comment]
I believe this question was answered a while ago.  Adding here for documentation.

[PROGHOR] asks a question with either 2 choices that can be selected or no response.  If either choice is made, there is a set of follow-up questions. We create a set of followup question for each choice. If there is no response, we skip to [COMBHOR].

So it should look like...
[PROGHOR] question text...
[1] choice 1 text -> PROGHOR2_1
[2] choice 2 text -> PROGHOR2_2
< -> COMBHOR>

[PROGHOR2_1] is the follow up question PROGHOR2 for the first choice
< ->  PROGHOR3_1

[PROGHOR3_1] is the follow up question PROGHOR3 for the first choice
< ->  PROGHOR4_1
....
[PROGHOR2_2] is the follow up question PROGHOR2 for the second choice
< -> PROGHOR3_2
...
[COMBHOR] Question text

For question [PROGHOR] you need to add the < -> COMBHOR>. This adds COMBHOR to the question list.  However, since you've added it to the list, after every question, you need to add <->XXX> so that the next question is set appropriately, and you do not jump to COMBHOR.  If you have both questions, both [PROGHOR2_2] and [COMHOR] are added to the question list, so when you dont specify where to go next, it first goes to [PROGHOR2_2] then it goes to [COMHOR] (unless you add questions via <->XXX>

Hope this clears it up.
